server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SybaseDialect
  datasource:
    isolation-level: SERIALIZABLE
    url: jdbc:sybase:Tds:localhost:2638/bancos
    username: DBA
    password: sql
    driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
  application:
    name: AppBanco
