server:
  port: 8085

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SybaseDialect
  datasource:
    isolation-level: SERIALIZABLE
    url: jdbc:sybase:Tds:localhost:2638/bancos
    username: DBA
    password: sql
    driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
  application:
    name: AppBanco
